server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml
  
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: scraper_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: scraper_logs
          __path__: /var/lib/docker/containers/*/*.log