server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml
  
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: scraper_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_monitor_me]
        regex: "true"
        action: keep
      - target_label: job
        replacement: scraper_logs
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__



    # static_configs:
      # - targets:
      #     - localhost
      #   labels:
      #     job: scraper_logs
      #     __path__: /var/lib/docker/containers/*/*.log